# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: libluckman@libero.it
author_name: efo
contract_name: myhelloworld
deployment_language: python
preset_name: starter
project_name: myhelloworld

